version: "2"
services: 
  services: 
    build: .
    ports: 
    - "5000:5000"
    depends_on: 
    - db
  db:
    container_name: db
    image: mongo:4.0
    ports: 
      - "27017:27017"
    environment: 
      MONGO_INIDB_ROOT_USERNAME: mongoadmin
      MONGO_INIDB_ROOT_USERNAME: secret